name: ci

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:

  # post a comment linking to codesandbox with the current branch
  meta-demo-comment:
    name: meta/demo-comment
    runs-on: ubuntu-latest

    if: ${{ github.event == "pull_request" }}

    steps:
    - uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "Demo: <https://codesandbox.io/embed/github/${{ github.repository }}/tree/${{ github.head_ref }}?view=preview>"

  build-docker:
    name: build/docker
    runs-on: ${{ matrix.os }}

    if: ${{ github.event == "push" || github.event == "pull_request" }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - run: docker build -t docker.pkg.github.com/orangemug/editor-ci-test/editor:master .

  # build the editor
  build-node:
    name: "build/node@${{ matrix.node-version }} (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}

    if: ${{ github.event == "push" || github.event == "pull_request" }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm install
    - run: npm run build

  # build and test the editor in standalone-chrome
  test_selenium_standalone_chrome:
    name: "test/standalone-chrome (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}

    if: ${{ github.event == "push" || github.event == "pull_request" }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [10]

    container:
      image: node:${{ matrix.node-version }}
      options: --network-alias testhost

    services:
      selenium:
        image: selenium/standalone-chrome:3.141.59
        ports:
        - 4444:4444

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm install
    - run: DOCKER_HOST=selenium npm test
    - run: ./node_modules/.bin/istanbul report --include build/artifacts/coverage/coverage.json --dir build/artifacts/coverage html lcov
    - uses: actions/upload-artifact@v1
      with:
        name: coverage
        path: build/artifacts/coverage

