name: meta

on:
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  check_suite:
    types:
      - completed

jobs:

  # post a comment linking to codesandbox with the current branch
  meta-demo-comment:
    name: meta/demo-comment
    runs-on: ubuntu-latest

    steps:
    - run: echo "github.event_name=${{ github.event_name }}"
    - uses: unsplash/comment-on-pr@v1.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "Demo: <https://codesandbox.io/embed/github/${{ github.repository }}/tree/${{ github.head_ref }}?view=preview>"
